### ISSUE TITLE
android and ios support

### ISSUE THREAD

**Issue by Techdaan** [W2Codam/MLX42#8]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't test my stuff on my phone

**Describe the solution you'd like**
It to work on my phone.

**Describe alternatives you've considered**
Opening a feature request.

**Additional context**
Make it work on this screen pls![image](https://user-images.githubusercontent.com/12966625/155297345-e2bdf960-5bf4-4827-b141-97dac498b33a.png)

**Comment by W2Wizard** [comment]
No
